#!/bin/bash
cd "$( dirname "${BASH_SOURCE[0]}" )"

#################################################
# Loads the correct module
#
# @param $1: All parameters passed to Originator
#################################################
Originator_dispatch() {
    IFS=':' read -ra segment <<< "$1"
    for part in "${segment[@]}"; do
        module_location="./modules/$part"
        bootstrap_file="$module_location/bootstrap.bash"
        if [ -e "$bootstrap_file" ]; then
            cd "$module_location";
            . "bootstrap.bash"
        else
            echo "Module $part does not exist."
        fi
        break
    done
}

#################################################
# Loads all of the autoload files
#################################################
Originator__autoload() {
    for file in "$1"/*; do
        . "$file"
    done
}

#################################################
# Start
#################################################
Originator__autoload lib
Originator__autoload config
Originator_dispatch "$@"

